version: "3.5"

services:
  flask:
    image: "python:${PYTHON_TAG}"
    container_name: "${PROJECT_NAME}_flask"
    hostname: flask
    stop_grace_period: 60s
    restart: always
    environment:
      FLASK_APP: "app.py"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "5000"
      FLASK_ENV: $FLASK_ENV
      FLASK_DEBUG: $FLASK_DEBUG
      IMAGE_DIR: "/home/app/images"
      OUT_DIR: "/home/app/out"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "${FLASK_PORT}:5000"
    depends_on:
      - redis
    ulimits:
      memlock:
        soft: -1
        hard: -1
    build: 
      dockerfile: Dockerfile
      context: ./server
      args:
        PYTHON_TAG: $PYTHON_TAG
    command: gunicorn app:app --worker-class gevent --workers=3 --threads=3 -b :5000 --timeout 600 --reload --access-logfile -
    volumes: 
      - .:/home/app 
      - ./server:/app

  celery:
    image: "python:${PYTHON_TAG}"
    container_name: "${PROJECT_NAME}_celery"
    hostname: celery
    stop_grace_period: 60s
    restart: always
    environment:
      FLASK_APP: "app.py"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "5000"
      FLASK_ENV: $FLASK_ENV
      FLASK_DEBUG: $FLASK_DEBUG
      IMAGE_DIR: "/home/app/images"
      OUT_DIR: "/home/app/out"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      C_FORCE_ROOT: "true"
    depends_on:
     - redis
     - flask
    ulimits:
      memlock:
        soft: -1
        hard: -1
    build: 
      dockerfile: Dockerfile
      context: ./server
      args:
        PYTHON_TAG: $PYTHON_TAG
    command: celery --app app.celery worker --loglevel=info
    volumes: 
      - .:/home/app 
      - ./server:/app

  vue:
    image: "node:${NODE_TAG}"
    container_name: "${PROJECT_NAME}_vue"
    hostname: vue
    stop_grace_period: 60s
    restart: always
    environment:
      NODE_ENV: $NODE_ENV
      FLASK_HOST: "nginx_flask"
      FLASK_PORT: "80"
      CHOKIDAR_USEPOLLING: $CHOKIDAR_USEPOLLING
    ports:
      - "${NGINX_VUE_PORT}:8080"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    build: 
      dockerfile: Dockerfile_dev
      context: ./client
      args:
        NODE_TAG: $NODE_TAG
        NGINX_TAG: $NGINX_TAG
    volumes:  
      - .:/home/app 
      - ./client:/app
    
  nginx_flask:
    image: "nginx:${NGINX_TAG}"
    container_name: "${PROJECT_NAME}_nginx_flask"
    hostname: nginx_flask
    stop_grace_period: 60s
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: $JUPYTER_ENABLE_LAB
    depends_on:
      - flask
    ports:
      - "${NGINX_FLASK_PORT}:80"
    volumes:
      - ./server/services/nginx/conf.d:/etc/nginx/conf.d

  flower:  
    image: mher/flower:${FLOWER_TAG}
    container_name: "${PROJECT_NAME}_flower"
    hostname: flower
    stop_grace_period: 60s
    restart: always
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      FLOWER_PORT: "8888"
    ports:  
      - "${FLOWER_PORT}:8888"

  jupyter:
    image: "jupyter/tensorflow-notebook:${JUPYTER_TAG}"
    container_name: "${PROJECT_NAME}_jupyter"
    hostname: jupyter
    stop_grace_period: 60s
    restart: always
    ports:
      - "${JUPYTER_PORT}:8888"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    build: 
      dockerfile: Dockerfile
      context: ./jupyter
      args:
        JUPYTER_TAG: $JUPYTER_TAG
    volumes:
      - .:/home/jovyan/work
                
  redis:
    image: "redis:${REDIS_TAG}"
    container_name: "${PROJECT_NAME}_redis"
    stop_grace_period: 60s
    hostname: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  portainer:
    image: "portainer/portainer:${PORTAINER_TAG}"
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    hostname: portainer
    stop_grace_period: 60s
    restart: always
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     
networks:
  default:
      name: dolphin_segmentation      
